In [1]:
import numpy as np
import pandas as pd

C:\Users\Sandhya Verma\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
data= pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'],inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [6]:
#problem 1

#Outlook= Sunny,Temp=Hot,Humidity=High,wind=Weak
#Play or No Play?

In [4]:
#Solution
#P(Yes /Sunny,Hot,High,Weak)= P(Sunny/YES)*P(HOT/Yes)*P(High /YEs)*P(Weak /Yes)
#P(No /Sunny,Hot,High,Weak)= P(Sunny/No)*P(HOT/No)*P(High /No)*P(Weak /No)
#compare and decide using the maximum a posteriori rule

In [5]:
#Problem 2
#Outlook=Overcast,Temp=Cold,Humidity=Low,Wind=Weak
#Play or No play?

In [6]:
#Solution
#P(Yes /Overcast,Cold,Low,Weak)= P(OverCast/YES)*P(Cold/Yes)*P(Low /YEs)*P(Weak /Yes)
#P(No /Overcast,Cold,Low,Weak)= P(Overcast/No)*P(Cold/No)*P(Low /No)*P(Weak /No)
#compare and decide using the maximum a posteriori rule

In [7]:
#Training
#Lookup Table(Dictionary)
#Testing

In [8]:
#P(YES)
#P(NO)

In [9]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
py=9/14
pn= 5/14

In [11]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [12]:
#Outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [14]:
#temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
Pcn=1/5
Phn=2/5
PMn=2/5

Pcy=3/9
PHy=2/9
PMy=4/9

In [16]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
phn=4/5
pnn=1/5

phy=3/9
pny=6/9

In [18]:
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
psn=3/5
pwn=2/5

psy=3/9
pwy=6/9

In [21]:


#Outlook= Sunny,Temp=Hot,Humidity=High,Wind=Weak

Pyes= py*Psy*PHy*phy*pwy
print(Pyes)

0.007054673721340388

In [22]:
Pno= py*Psn*Phn*phn*pwn
print(Pno)

0.04937142857142858